### ISSUE TITLE
TextInput ref not working 

### ISSUE THREAD

**Issue by AbiramanK** [react-native-packages/react-native-design#2]
While trying to clear TextInput value by using ref then it's not working

**Comment by Pedrinvits** [comment]
> While trying to clear TextInput value by using ref then it's not working


To clear a TextInput value in React Native using a ref, follow these steps:

Create a ref for the TextInput.
Attach the ref to the TextInput component.
Call the clear method on the ref to clear the value.
`import React, { useRef } from 'react';
import { View, TextInput, Button } from 'react-native';

const MyComponent = () => {
  const textInputRef = useRef(null);

  const clearTextInput = () => {
    if (textInputRef.current) {
      textInputRef.current.clear();
    }
  };

  return (
    <View>
      <TextInput
        ref={textInputRef}
        placeholder="Type something"
      />
      <Button title="Clear Text" onPress={clearTextInput} />
    </View>
  );
};
`

**Comment by AbiramanK** [comment]
@Pedrinvits Thank you for your comments.

The issue is resolved by using your solution.
